ForumBundle\Entity\Forum:
    type: entity
    table: forum
    indexes:
        user_id:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        countTopics:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: count_topics
        countPosts:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: count_posts
        createdAt:
            type: datetime
            nullable: false
            column: created_at
    manyToOne:
        user:
            targetEntity: User
            cascade: { remove, persist }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumn:
                nullable: false
                onDelete: CASCADE
                onUpdate: CASCADE
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: { prePersist: [ setCreatedAtValue ] }
