ForumBundle\Entity\Post:
    repositoryClass: ForumBundle\Entity\PostRepository
    type: entity
    table: post
    indexes:
        topic_id:
            columns:
                - topic_id
        user_id:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        text:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
    manyToOne:
        topic:
            targetEntity: Topic
            cascade: { remove, persist }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumn:
                nullable: false
                onDelete: CASCADE
                onUpdate: CASCADE
                topic_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: User
            cascade: { remove, persist }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumn:
                nullable: false
                onDelete: CASCADE
                onUpdate: CASCADE
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: { prePersist: [ setCreatedAtValue ] }
