ForumBundle\Entity\Post:
    repositoryClass: ForumBundle\Entity\PostRepository
    type: entity
    table: post
    indexes:
        topic_id:
            columns:
                - topic_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        text:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        createdDate:
            type: datetime
            nullable: false
            column: created_date
    manyToOne:
        topic:
            targetEntity: Topic
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                topic_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
