ForumBundle\Entity\Topic:
    repositoryClass: ForumBundle\Entity\TopicRepository
    type: entity
    table: topic
    indexes:
        forum_id:
            columns:
                - forum_id
        user_id:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        closed:
            type: boolean
            nullable: false
            options:
                default: '0'
        fixed:
            type: boolean
            nullable: false
            options:
                default: '0'
        countPosts:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: count_posts
        createdAt:
            type: datetime
            nullable: false
            column: created_at
    manyToOne:
        forum:
            targetEntity: Forum
            cascade: [ remove, persist ]
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumn:
                nullable: false
                onDelete: CASCADE
                onUpdate: CASCADE
                forum_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: User
            cascade: [ remove, persist ]
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumn:
                nullable: false
                onDelete: CASCADE
                onUpdate: CASCADE
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: { prePersist: [ setCreatedAtValue ] }
