ForumBundle\Entity\User:
    type: entity
    table: user
    uniqueConstraints:
        username:
            columns:
                - username
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        roles:
            type: array
        password:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        salt:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        sex:
            type: string
            nullable: true
            columnDefinition: ENUM('m', 'f')
            options:
                default: null
    lifecycleCallbacks: { prePersist: [ setCreatedAtValue ] }
