language: php

php:
    - 5.6
    - 7.0
    - hhvm
    - nightly

env:
    global:
        - MIN_PHP=5.6.5
        - SYMFONY_ENV=test

services:
    - mysql

cache:
    directories:
        - vendor
        - $HOME/.composer/cache/files
        - php-$MIN_PHP

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source

before_script:
    - cp app/config/parameters.yml.travis app/config/parameters.yml
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:schema:create --env=test
    - php bin/console doctrine:fixtures:load -n --env=test

script:
    - bin/phpunit --configuration phpunit.xml.dist

notifications:
    email:
        on_failure: change
