language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - hhvm
    - nightly

env:
    global:
        - MIN_PHP=5.6.5
        - SYMFONY_ENV=test

services:
    - mysql

cache:
    directories:
        - vendor
        - $HOME/.composer/cache/files
        - php-$MIN_PHP

before_install:
  - composer self-update
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - mysql -e 'CREATE DATABASE IF NOT EXISTS forum_test'

install:
  - travis_retry composer install --no-interaction --prefer-source
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

before_script:
    - chmod 755 bin/console
    - chmod 755 bin/phpunit

script:
    - bin/phpunit --configuration phpunit.xml.dist

notifications:
    email:
        on_failure: change
