forum_show:
    path:     /forum{id}/{page}
    defaults: { _controller: ForumBundle:Forum/Forum:show, page: 1 }
    requirements:
        id:   \d+
        page: \d+

topic_show:
    path:     /topic{id}/{page}
    defaults: { _controller: ForumBundle:Forum/Topic:show, page: 1 }
    requirements:
        id:   \d+
        page: \d+

topic_add:
    path:     /forum{id}/add_topic
    defaults: { _controller: ForumBundle:Forum/Topic:new }
    methods:  [POST]
    requirements:
        id:   \d+

post_add:
    path:     /topic{id}/add_post
    defaults: { _controller: ForumBundle:Forum/Post:new }
    methods:  [POST]
    requirements:
        id:   \d+

