forum_show:
    path:     /forum{id}/{page}
    defaults: { _controller: ForumBundle:Forum/Forum:show, page: 1 }
    requirements:
        id:   \d+
        page: \d+

topic_show:
    path:     /topic{id}/{page}
    defaults: { _controller: ForumBundle:Forum/Topic:show, page: 1 }
    requirements:
        id:   \d+
        page: \d+

topic_add:
    path:     /forum{id}/add_topic
    defaults: { _controller: ForumBundle:Forum/Topic:new }
    methods:  [POST]
    requirements:
        id:   \d+

topic_edit:
    path:     /topic{id}/edit
    defaults: { _controller: ForumBundle:Forum/Topic:edit }
    methods:  [POST]
    requirements:
        id:   \d+

topic_delete:
    path:     /topic{id}/delete
    defaults: { _controller: ForumBundle:Forum/Topic:delete }
    methods:  [POST]
    requirements:
        id:   \d+

post_add:
    path:     /topic{id}/add_post
    defaults: { _controller: ForumBundle:Forum/Post:new }
    methods:  [POST]
    requirements:
        id:   \d+

post_edit:
    path:     /post{id}/edit
    defaults: { _controller: ForumBundle:Forum/Post:edit }
    methods:  [POST]
    requirements:
        id:   \d+

post_delete:
    path:     /post{id}/delete
    defaults: { _controller: ForumBundle:Forum/Post:delete }
    methods:  [POST]
    requirements:
        id:   \d+

profile_show:
    path:     /profile{id}
    defaults: { _controller: ForumBundle:Forum/Profile:show }
    requirements:
        id:   \d+

profile_edit:
    path:     /profile{id}/edit
    defaults: { _controller: ForumBundle:Forum/Profile:edit }
    requirements:
        id:   \d+

profile_delete:
    path:     /profile{id}/delete
    defaults: { _controller: ForumBundle:Forum/Profile:delete }
    requirements:
        id:   \d+