post_new:
    path:     /{id}/new
    defaults: { _controller: "ForumBundle:Post:new" }
    methods:  [GET, POST]
    requirements:
        id:   \d+

#post_edit:
#    path:     /{id}/edit
#    defaults: { _controller: "ForumBundle:Post:edit" }
#    methods:  [GET, POST]

#post_delete:
#    path:     /{id}/delete
#    defaults: { _controller: "ForumBundle:Post:delete" }
#   methods:  DELETE
