index:
    path:  /
    defaults: { _controller: ForumBundle:Default:index }

forum:
    path:  /forum/{id}
    defaults: { _controller: ForumBundle:Default:forum }
topic:
    path:  /topic/{id}
    defaults: { _controller: ForumBundle:Default:topic }