index:
    path:  /
    defaults: { _controller: ForumBundle:Default:index }

forum:
    resource: "@ForumBundle/Resources/config/routing/forum.yml"
    prefix:   /forum

topic:
    resource: "@ForumBundle/Resources/config/routing/topic.yml"
    prefix:   /topic

post:
    resource: "@ForumBundle/Resources/config/routing/post.yml"
    prefix:   /post
