index:
    path:  /
    defaults: { _controller: ForumBundle:Default:index }

forum:
    path:  /forum{id}/{page}
    defaults: { _controller: ForumBundle:Default:forum, page: 1 }
    requirements:
        id:       \d+
        page:     \d+

topic:
    path:  /topic{id}/{page}
    defaults: { _controller: ForumBundle:Default:topic, page: 1 }
    requirements:
        id:       \d+
        page:     \d+
