index:
    path:  /
    defaults: { _controller: ForumBundle:Default:index }

forum:
    resource: "@ForumBundle/Resources/config/routing/forum.yml"
    prefix:   /forum


# Login
login_route:
    path:     /login
    defaults: { _controller: ForumBundle:Security:login }

login_check:
    path: /login_check

logout:
   path: /logout