index:
    path:  /
    defaults: { _controller: ForumBundle:Default:index }

forum:
    path:  /forum{id}
    defaults: { _controller: ForumBundle:Default:forum }
topic:
    path:  /topic{id}/page{page}
    defaults: { _controller: ForumBundle:Default:topic, page: 1 }
    requirements:
        methods:  GET
        page:     \d+
#pager:
#    path: page{page}
#    defaults: { page: 1 }
#    requirements:
#        page: \d+