ForumBundle\Entity\Forum:
    properties:
        title:
            - NotBlank: ~
            - Length:
                min: 2
                minMessage: 'FMin {{ limit }} symbols'

ForumBundle\Entity\Topic:
    properties:
        title:
            - NotBlank: ~
            - Length:
                min: 2
                minMessage: 'TMin {{ limit }} symbols'

ForumBundle\Entity\Post:
    properties:
        text:
            - NotBlank: ~
            - Length:
                min: 2
                minMessage: 'PMin {{ limit }} symbols'
