ForumBundle\Entity\Forum:
    properties:
        title:
            - NotBlank:
                message: 'Название форума не должно быть пустым'
            - Length:
                min: 2
                minMessage: 'Минимально {{ limit }} символа(ов)'

ForumBundle\Entity\Topic:
    properties:
        title:
            - NotBlank:
                message: 'Название топика не должно быть пустым'
            - Length:
                min: 2
                minMessage: 'Минимально {{ limit }} символа(ов)'

ForumBundle\Entity\Post:
    properties:
        text:
            - NotBlank:
                message: 'Сообщение не должно быть пустым'
            - Length:
                min: 2
                minMessage: 'Минимально {{ limit }} символа(ов)'
