ForumBundle\Entity\Forum:
    properties:
        title:
            - NotBlank:
                message: 'Название форума не должно быть пустым'
            - Length:
                min: 2
                minMessage: 'Название форума должно содержать не менее {{ limit }} символа(ов)'

ForumBundle\Entity\Topic:
    properties:
        title:
            - NotBlank:
                message: 'Название топика не должно быть пустым'
            - Length:
                min: 2
                minMessage: 'Название топика должно содержать не менее {{ limit }} символа(ов)'

ForumBundle\Entity\Post:
    properties:
        text:
            - NotBlank:
                message: 'Сообщение не должно быть пустым'
            - Length:
                min: 2
                minMessage: 'Сообщение должно содержать не менее {{ limit }} символа(ов)'

ForumBundle\Entity\User:
    properties:
        username:
            - NotBlank:
                message: 'Логин не должен быть пустым'
                groups: [registration]
            - Length:
                min: 3
                minMessage: 'Логин должен содержать не менее {{ limit }} символа(ов)'
                groups: [registration]
        plainPassword:
            - NotBlank:
                message: 'Пароль не должен быть пустым'
                groups: [registration]
            - Length:
                min: 8
                minMessage: 'Пароль должен содержать не менее {{ limit }} символа(ов)'
                groups: [registration]

ForumBundle\Model\ChangePassword:
    properties:
        currentPlainPassword:
            - Symfony\Component\Security\Core\Validator\Constraints\UserPassword:
                message: 'Введите действующий пароль!'
        plainPassword:
            - NotBlank:
                message: 'Пароль не должен быть пустым'
                groups: [registration]
            - Length:
                min: 8
                minMessage: 'Пароль должен содержать не менее {{ limit }} символа(ов)'
                groups: [registration]
