-- MySQL Script generated by MySQL Workbench
-- 01/07/16 18:57:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`forum` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `title` TEXT NOT NULL COMMENT '',
  `count_topics` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '',
  `count_posts` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '',
  `position` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`topic` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `title` TEXT NOT NULL COMMENT '',
  `forum_id` INT UNSIGNED NOT NULL COMMENT '',
  `closed` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '',
  `count_posts` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_forum_id` (`forum_id` ASC)  COMMENT '',
  CONSTRAINT `topic_use_forum_id`
    FOREIGN KEY (`forum_id`)
    REFERENCES `mydb`.`forum` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`post` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `text` TEXT NOT NULL COMMENT '',
  `topic_id` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_topic_id` (`topic_id` ASC)  COMMENT '',
  CONSTRAINT `post_use_topic_id`
    FOREIGN KEY (`topic_id`)
    REFERENCES `mydb`.`topic` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
